SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Galaxy Runner"

TILE_SCALING = 0.5
CHARACTER_SCALING = 0.5
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = SPRITE_PIXEL_SIZE * TILE_SCALING

PLAYER_MOVEMENT_SPEED = 5
GRAVITY = 1.0
PLAYER_JUMP_SPEED = 22
PLAYER_DOUBLE_JUMP_SPEED = 18
MAX_JUMPS = 2

PLAYER_LIVES = 3

PLAYER_START_X = 128
PLAYER_START_Y = 256

LEVELS = [
    "resources/maps/level_1.txt",
    "resources/maps/level_2.txt",
]

HIGHSCORE_FILE = "resources/highscore.txt"
